---

- name: Ensure nginx will reinstall if the PPA was just added.
  apt_repository:
    repo: 'ppa:nginx/stable'
  when: ansible_distribution_version <= '22.04'

- name: Ensure nginx will reinstall if the PPA was just added.
  apt:
    name: nginx
    state: present
    update_cache: true
  when: ansible_distribution_version >= '22.04'
