---
- name: Converge
  hosts: all
  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: Ensure dirmngr is installed (gnupg dependency).
      apt:
        name: dirmngr
        state: present
      when: ansible_os_family == 'Debian'
  roles:
    - role: ansible-role-nginx
