---
- name: Check that nginx file has been created
  hosts: all
  become: yes
  
  tasks:
  - name: Check that nginx file has been created
    stat:
      path: /etc/nginx
    register: stat_result
    
  - name: Check that alternate nginx log for use behind load balancer has been created
    stat:
      path: /etc/nginx/conf.d/log_format_proxied.conf
    register: stat_result

  - name: check if nginx has port 80 open
    shell: netstat -tunlp | grep ":80 " | sed -e 's/.*\///'
    register: results

  - name: See what netstat returned
    debug: var=results
